package cn.qcofa.com.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF32226F)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFF4C3889)
val LightOnPrimaryContainer = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFF4B425D)
val LightOnSecondaryContainer = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFF6C3644)
val LightOnTertiaryContainer = Color(0xFFFFFFFF)
val LightSurface = Color(0xFFFAF8FE)
val LightSurfaceContainerLow = Color(0xFFF5F3F8)
val LightSurfaceContainer = Color(0xFFEFEDF2)
val LightSurfaceContainerHigh = Color(0xFFE9E7ED)
val LightSurfaceContainerHighest = Color(0xFFE4E1E7)
val LightOnSurface = Color(0xFF010002)
val LightOnSurfaceVariant = Color(0xFF1D1A23)
val LightOutline = Color(0xFF322F39)
val LightOutlineVariant = Color(0xFF322F39)
val LightInverseSurface = Color(0xFF313034)
val LightInverseOnSurface = Color(0xFFF2F0F5)
val LightInversePrimary = Color(0xFFD2BCFC)
val LightError = Color(0xFFB3261E)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFF9DEDC)
val LightOnErrorContainer = Color(0xFF410E0B)

val DarkPrimary = Color(0xFFF4EEFE)
val DarkOnPrimary = Color(0xFF010003)
val DarkPrimaryContainer = Color(0xFFD2BCFC)
val DarkOnPrimaryContainer = Color(0xFF010003)
val DarkSecondaryContainer = Color(0xFFCDC1E1)
val DarkOnSecondaryContainer = Color(0xFF010003)
val DarkTertiaryContainer = Color(0xFFF6B5C3)
val DarkOnTertiaryContainer = Color(0xFF020000)
val DarkSurface = Color(0xFF141317)
val DarkSurfaceContainerLow = Color(0xFF1C1B1F)
val DarkSurfaceContainer = Color(0xFF201F23)
val DarkSurfaceContainerHigh = Color(0xFF2B292D)
val DarkSurfaceContainerHighest = Color(0xFF363438)
val DarkOnSurface = Color(0xFFFFFFFF)
val DarkOnSurfaceVariant = Color(0xFFF3EFFC)
val DarkOutline = Color(0xFFE5E0ED)
val DarkOutlineVariant = Color(0xFFE5E0ED)
val DarkInverseSurface = Color(0xFFE4E1E7)
val DarkInverseOnSurface = Color(0xFF313034)
val DarkInversePrimary = Color(0xFF6750A4)
val DarkError = Color(0xFFF2B8B5)
val DarkOnError = Color(0xFF601410)
val DarkErrorContainer = Color(0xFF8C1D18)
val DarkOnErrorContainer = Color(0xFFF9DEDC)