plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'cn.qcofa.com'
    compileSdk 34

    defaultConfig {
        applicationId "cn.qcofa.com"
        minSdk 24
        targetSdk 34
        versionCode 5
        versionName "1.5.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            storeFile file('/workspace/release.keystore')
            storePassword 'qcofa123'
            keyAlias 'qcofa'
            keyPassword 'qcofa123'
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}